//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.cardpackage {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtPID;
		protected global::System.Web.UI.WebControls.TextBox txtCID;
		protected global::System.Web.UI.WebControls.TextBox txtpickerID;
		protected global::System.Web.UI.WebControls.TextBox txtpackageID;
		protected global::System.Web.UI.WebControls.TextBox txtSelectTime;
		protected global::System.Web.UI.WebControls.TextBox txtTableID;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
