//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zmdbEntities1 : DbContext
    {
        public zmdbEntities1()
            : base("name=zmdbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cards> cards { get; set; }
        public virtual DbSet<game> game { get; set; }
        public virtual DbSet<gamepackage> gamepackage { get; set; }
        public virtual DbSet<packagecard> packagecard { get; set; }
        public virtual DbSet<sets> sets { get; set; }
        public virtual DbSet<table> table { get; set; }
        public virtual DbSet<userontable> userontable { get; set; }
        public virtual DbSet<userpackage> userpackage { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
