//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class packagecard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public packagecard()
        {
            this.userpackage = new HashSet<userpackage>();
        }
    
        public long packagecardid { get; set; }
        public int gamepackageid { get; set; }
        public int cardid { get; set; }
        public Nullable<int> pickituserid { get; set; }
    
        public virtual cards cards { get; set; }
        public virtual gamepackage gamepackage { get; set; }
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userpackage> userpackage { get; set; }
    }
}
