//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class userontable
    {
        public int id { get; set; }
        public int userid { get; set; }
        public int tableid { get; set; }
        public int rank { get; set; } 
        [JsonIgnore]
        public virtual table table { get; set; }
        [JsonIgnore]
        public virtual users users { get; set; }
    }
}
