//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.cards {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblCID;
	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblName;
	protected global::System.Web.UI.WebControls.Label lblXiYouDu;
	protected global::System.Web.UI.WebControls.Label lblFeiYong;
	protected global::System.Web.UI.WebControls.Label lblZhongCheng;
	protected global::System.Web.UI.WebControls.Label lblWLTL;
	protected global::System.Web.UI.WebControls.Label lblType1;
	protected global::System.Web.UI.WebControls.Label lblType2;
	protected global::System.Web.UI.WebControls.Label lblXiLie;
	protected global::System.Web.UI.WebControls.Label lblXiLieID;
	protected global::System.Web.UI.WebControls.Label lblNengLi;


       
    }
}
